---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - curl
    - apt-transport-https
    - ca-certificates
    - apparmor

- name: add docker repository for Debian
  shell: add-apt-repository "deb https://apt.dockerproject.org/repo/ debian-$(lsb_release -cs) main"
  when: ansible_distribution == "Debian"

- name: add docker repository for Ubuntu
  shell: add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"
  when: ansible_distribution == "Ubuntu"

- name: add key id
  apt_key:
    url: "https://yum.dockerproject.org/gpg"
    state: present

- name: install docker
  apt:
    name: docker-engine
    update_cache: yes
    state: present

- name: add user to docker group
  user: name={{ docker_user }} groups=docker append=yes

- name: Ensure docker-compose is installed and available
  get_url:
      url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x,o+x'