---

- name: make sure dnf-plugins.core installed
  dnf:
    name: dnf-plugins-core
    state: present

- name: install repository
  command: dnf config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/fedora/docker.repo

- name: make sure docker from distro is not installed
  dnf:
    name: docker
    state: absent

- name: install docker
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-engine
    - python-docker-py
    - python-pip