---

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: install docker repository
  shell:  yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo

- name: make sure docker from distro is not installed
  yum:
    name: docker
    state: absent

- name: Install docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-engine
    - python-docker-py

- name: making sure pip installed
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python
