---
- name: Add the webupd8 APT repository key
  # Use a static file because right now using just an ID fails
  apt_key: data="{{ lookup('file', 'webupd8.key.asc') }}" state=present

- name: Add the webupd8 APT repository
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Java
  apt:
    name: oracle-java8-set-default
    update-cache: yes
    state: latest